### ISSUE TITLE
Rename Nette\Object (name reserved in PHP 7)

### ISSUE THREAD

**Issue by Majkl578** [nette/utils#59]
There are currently two RFCs [1] [2] in voting phase, both introducing reserved types in PHP 7. This includes "object", which, if the vote passes, will be illegal as a class/interface/trait name.

Sadly, this <del>will be</del> *may - in 7.x - become* a serious BC break with nearly impossible backward compatibility for almost all user-land applications.

[1] https://wiki.php.net/rfc/reserve_more_types_in_php_7
[2] https://wiki.php.net/rfc/reserve_even_more_types_in_php_7

**Comment by dg** [comment]
> This RFC does not fully reserve them as keywords; it only prohibits their usage as class, interface and trait names. It also prevents them from being used in namespaces.

From my point is name `Nette\Object` fine.

**Comment by Majkl578** [comment]
No, it is not. See http://3v4l.org/T01QS/rfc#tabs (example with Int, which is the same case, 2nd rfc just doesn't have implementation yet)

**Comment by dg** [comment]
I have asked here https://twitter.com/geekovo/status/577528995341828096. In case that is really problem we would have to send emails to all the people that voted for it. "Good news" is that it will break Zend Framework too. https://github.com/zendframework/zf2/blob/master/library/Zend/Form/Annotation/Object.php

**Comment by dg** [comment]
https://twitter.com/SaraMG/status/577532526261968897

**Comment by dg** [comment]
This is important https://twitter.com/SaraMG/status/577555210471510016.

**Comment by JanTvrdik** [comment]
Also important: http://thread.gmane.org/gmane.comp.php.devel/97842/focus=97953 She is basically saying that `Nette\Object` will work fine in PHP 7 but they it may stop working in the future.

**Comment by Majkl578** [comment]
@JanTvrdik: That is exactly the point. It may not be throwing error in 7.0, but suddenly in 7.1 it may become a typehint and thus start throwing fatals. And Nette would not have enough time to properly transition. Better sooner than later.

**Comment by Majkl578** [comment]
RFC has been accepted: http://news.php.net/php.internals/85738, thus `Object` is now a dangerous name.

**Comment by richard-ejem** [comment]
I would consider if Object is still needed / proper stuff to use. It actually combines several different features and I don't see any reason to combine them into a "base object":

* Reflection factory - I don't think it should be a method of Object, we can get reflection via new Nette\Reflection\ClassType($object)
* Object mixin - from PHP 5.4 we have traits for this
* Dynamically adding methods via extensionMethod - this isn't anyway the best practice one can use
* Magic getters and setters using get*() and set*() methods

My suggestion would be:
* create reflection objects from the point of reflection class
* use traits instead of generic object mixin
* add support for magic getters/setters by using dedicated trait (i.e. TMagicGettersSetters); I personally don't use them anymore, because it is a magic that doesn't save so much coding or improve readability (actually makes the code less readable)
* create a special trait for extensionMethod
* make \Nette\Object deprecated ASAP

Yes, this would mean to drop support for PHP 5.3 as it does not support traits, but I think it would be OK to drop it now.

**Comment by juniwalk** [comment]
All I care about from `Nette\Object` is the strictness it brings to classes. I'd love to have `use Nette\Strict` trait.

**Comment by dg** [comment]
related https://forum.nette.org/cs/25958-jak-se-vyporadat-s-nette-object
